"""empty message

Revision ID: 9e993431608d
Revises: 803f5af9bca8
Create Date: 2021-05-04 16:55:06.574408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e993431608d'
down_revision = '803f5af9bca8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employees', 'salary',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('employees', 'birthday',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employees', 'birthday',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('employees', 'salary',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
