"""empty message

Revision ID: 9f2fad9ea8f7
Revises: 1e57761517a6
Create Date: 2021-04-26 18:04:56.071536

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f2fad9ea8f7'
down_revision = '1e57761517a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_employees_first_name', table_name='employees')
    op.create_index(op.f('ix_employees_first_name'), 'employees', ['first_name'], unique=False)
    op.drop_index('ix_employees_last_name', table_name='employees')
    op.create_index(op.f('ix_employees_last_name'), 'employees', ['last_name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_employees_last_name'), table_name='employees')
    op.create_index('ix_employees_last_name', 'employees', ['last_name'], unique=True)
    op.drop_index(op.f('ix_employees_first_name'), table_name='employees')
    op.create_index('ix_employees_first_name', 'employees', ['first_name'], unique=True)
    # ### end Alembic commands ###
